### ISSUE TITLE
Change csproj property name to be more specific

### ISSUE THREAD

**Issue by prajaybasu** [ronnygunawan/xbehave-specs#1]
Right now you need to add the following in csproj:

	<PropertyGroup>
	  <DocumentationFile>.\Documentation.xml</DocumentationFile>
	</PropertyGroup>

But <DocumentationFile> is not very specific and may clash with another library/project internally.

The property should be prefixed. For example, [ILLinker properties are prefixed](https://github.com/dotnet/core/blob/master/samples/linker-instructions-advanced.md) with `Linker`.

**Comment by ronnygunawan** [comment]
`<DocumentationFile>` is from csproj XSD.

However I noticed that the readme was not clear on this matter and [fixed it](https://github.com/ronnygunawan/xbehave-specs/commit/86a547be59d5a767eb84dcbde5366cc80afa8f6d)
